### ISSUE TITLE
Cannot find covenant-http

### ISSUE THREAD

**Issue by albx79** [lolgab/scala-fullstack#2]
What I do:

    ./mill -watch js.fastOpt

What I get:

    [30/47] js.compileClasspath | Downloading [12/12] artifacts (~0/0 bytes)
    1 targets failed
    js.compileClasspath 
    Resolution failed for 1 modules:
    --------------------------------------------
    com.github.cornerman.covenant:covenant-http_sjs0.6_2.13:master-SNAPSHOT 
            not found: /home/albx/.ivy2/local/com.github.cornerman.covenant/covenant-http_sjs0.6_2.13/master-SNAPSHOT/ivys/ivy.xml
            not found: https://repo1.maven.org/maven2/com/github/cornerman/covenant/covenant-http_sjs0.6_2.13/master-SNAPSHOT/covenant-http_sjs0.6_2.13-master-SNAPSHOT.pom
            not found: https://oss.sonatype.org/content/repositories/releases/com/github/cornerman/covenant/covenant-http_sjs0.6_2.13/master-SNAPSHOT/covenant-http_sjs0.6_2.13-master-SNAPSHOT.pom
            not found: https://jitpack.io/com/github/cornerman/covenant/covenant-http_sjs0.6_2.13/master-SNAPSHOT/covenant-http_sjs0.6_2.13-master-SNAPSHOT.pom

**Comment by lolgab** [comment]
I pushed an update and now everything should work fine.
